import "./globals.css";
import { roboto, montserrat } from "@/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable} bg-gray-100`}>
        <div className="flex min-h-screen flex-col items-center">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
